version: "3.9"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:80
    volumes:
      - ./:/var/www/html/
      - ./.docker/required_files/default.conf:/etc/apache2/sites-enabled/000-default.conf
    depends_on:
      - db
    networks:
      - app_network

  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: ${DB_NAME}
    volumes:
      - ./.docker/mysql-data:/var/lib/mysql
      - ./:/docker-entrypoint-initdb.d
    networks:
      - app_network

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
      - UPLOAD_LIMIT=100M
    networks:
      - app_network
    depends_on:
      - db

networks:
  app_network:
    driver: bridge
